# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "Efortless time tracking CLI tool"
  homepage "https://tristansch1.github.io/flow/"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TristanSch1/flow/releases/download/v0.2.0/flow_Darwin_x86_64.tar.gz"
      sha256 "761e9f1dd6f2e9069f6d9d7020abbf423358ceb7ecf3d474a4cf8992762f0f1a"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TristanSch1/flow/releases/download/v0.2.0/flow_Darwin_arm64.tar.gz"
      sha256 "03f0fc79f2fb55b809c0deccc3f8c297ed7b4649a0e85773e5ebb7b9953913c7"

      def install
        bin.install "flow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TristanSch1/flow/releases/download/v0.2.0/flow_Linux_x86_64.tar.gz"
      sha256 "4fcfc3afe17bbc539ba5bf49905ecde72728c5d435e6f902a5e1dfe9c16dcc49"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TristanSch1/flow/releases/download/v0.2.0/flow_Linux_arm64.tar.gz"
      sha256 "4a41bd114be88afe22afeb66002b35166ff9d49c1ec8cd37f3ae7188c0ac034d"

      def install
        bin.install "flow"
      end
    end
  end
end
